# Generated by Django 4.2.27 on 2026-03-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_folder", models.BooleanField(db_index=True, default=False)),
                (
                    "relative_path",
                    models.CharField(help_text="物理文件夹路径", max_length=1000),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("private", "私有"),
                            ("shared", "家庭共享"),
                            ("public", "公开链接"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=10,
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("extension", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app_files.filerecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "parent_folder"],
                        name="app_files_f_user_id_651e82_idx",
                    )
                ],
            },
        ),
    ]
