# Generated by Django 4.2.27 on 2026-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_files", "0002_uploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="filerecord",
            name="file_md5",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="filerecord",
            name="physical_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="filerecord",
            index=models.Index(
                fields=["file_md5"], name="app_files_f_file_md_eef088_idx"
            ),
        ),
    ]
