# Generated by Django 4.2.27 on 2026-03-09 07:20

import app_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_files", "0003_filerecord_file_md5_filerecord_physical_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filerecord",
            name="file_obj",
            field=models.FileField(
                blank=True, null=True, upload_to=app_files.models.user_directory_path
            ),
        ),
    ]
