# Generated by Django 4.2.27 on 2026-03-10 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mtime", models.BigIntegerField()),
                ("is_dir", models.BooleanField(default=False)),
                ("size", models.BigIntegerField(default=0)),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("extension", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="files.filenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("chunk_size", models.IntegerField()),
                ("total_chunks", models.IntegerField()),
                ("uploaded_chunks", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("upload_id", models.CharField(max_length=64, unique=True)),
                ("uploaded", models.BigIntegerField(default=0)),
                ("temp_path", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to="files.filenode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="filenode",
            index=models.Index(
                fields=["owner", "parent"], name="files_filen_owner_i_8eb9d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filenode",
            index=models.Index(fields=["sha256"], name="files_filen_sha256_4d172f_idx"),
        ),
    ]
