# Generated by Django 4.2.27 on 2026-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="mtime",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="filenode",
            name="mtime",
            field=models.BigIntegerField(null=True),
        ),
    ]
