# Generated by Django 4.2.27 on 2026-03-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_uploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="files.uploadsession",
            ),
        ),
    ]
