# Generated by Django 4.2.27 on 2026-03-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_uploadsession_mtime_alter_filenode_mtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadsession",
            old_name="file_size",
            new_name="size",
        ),
    ]
