# Generated by Django 4.2.27 on 2026-03-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_rename_file_size_uploadsession_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadsession",
            old_name="filename",
            new_name="name",
        ),
    ]
