# Generated by Django 4.2.27 on 2026-03-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_rename_filename_uploadsession_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="filenode",
            index=models.Index(
                fields=["owner", "parent", "name"],
                name="files_filen_owner_i_7f3c39_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="filenode",
            constraint=models.UniqueConstraint(
                fields=("owner", "parent", "name"), name="unique_file_in_directory"
            ),
        ),
    ]
